apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PostSync,PreDelete
spec:
  template:
    spec:
      serviceAccountName: migrator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec: {}
