apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  generateName: migrate-
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      serviceAccountName: migrator
